name: Nodejs-Ci
on:
    push:
      branches:
        - dev 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm install
      
      - name: run Test
        run: npm test

      # - name: Generate Coverage
      #   run: npx nyc npm test
      - name: Generate Coverage
        run: |
          npx nyc \
          --reporter=lcov \
          --reporter=text \
          npm test
      - name: Check Coverage Files
        run: |
         ls
         ls coverage
         cat coverage/lcov.info

      - name: SonarQube 
        run: |
         npx sonar-scanner \
         -Dsonar.projectKey=${{ vars.PROJECT_KEY }} \
         -Dsonar.organization=${{ vars.ORG_NAME }} \
         -Dsonar.host.url=https://sonarcloud.io \
         -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.NODE_TO_DO }}